Add a new source parameter: `snippetIndicator`
Shougo/ddc-source-nvim-lsp pull request #48
Opened 2023-08-06 12:32 UTC by 110y

### What

- Add the `snippetIndicator` parameter to change the indicator string for snippet completion candidates.

### Why

With recent (huge 👏) updates, now `ddc-source-nvim-lsp` adds an indicator string: `~`, to snippet completion candidates. While it should work well for the majority of users, I think there might be a user who wants to change this string (in my case, I just want to remove `~`).

Given that, this PR adds a new source parameter named `snippetIndicator` that enables us to change the indicator string for snippet completion candidates to an arbitrary string (including an empty string).

2023-08-06 23:37 UTC, Shougo requested changes
Please fix the CI.

2023-08-06 23:38 UTC, Shougo commented on denops/@ddc-sources/nvim-lsp.ts
> +  snippetIndicator: string
```suggestion
  snippetIndicator: string;
```

2023-08-06 23:41 UTC, Shougo commented on doc/ddc-source-nvim-lsp.txt
> +		a completion candidate.
```suggestion
		a completion item.
```

2023-08-06 23:43 UTC, Shougo commented on denops/ddc-source-nvim-lsp/completion_item.ts
> +    snippetIndicator: string,
```suggestion
    snippetIndicator: string,
    defaults?: LSP.CompletionList["itemDefaults"],
```

The optional parameter must be the last.

2023-08-06 23:46 UTC, uga-rosa commented
`deno task pre-commit` is available to perform the local equivalent of a CI check.

2023-08-07 00:10 UTC, Shougo commented on doc/ddc-source-nvim-lsp.txt
> +		The indicator string for snippet items added to the end of
It should be documented that it changes `ddc-item-attribute-abbr`.

2023-08-07 01:40 UTC, 110y commented
Thank you for your review!
Let me fix it...

2023-08-11 07:02 UTC, 110y commented
@Shougo @uga-rosa 

Sorry for the delay, I just handled all of your review comments.
I appreciate it if you could take another look 🙏

2023-08-11 07:10 UTC, uga-rosa requested changes

2023-08-11 07:10 UTC, uga-rosa commented on denops/@ddc-sources/nvim-lsp.ts
> +          args.sourceParams.snippetIndicator,
This is not something that changes from `item` to `item`. It should be passed in the CompletioinItem constructor since it is the same every time.

2023-08-11 08:48 UTC, 110y commented on denops/@ddc-sources/nvim-lsp.ts
> +          args.sourceParams.snippetIndicator,
Fixed 👍  Please take another look 🙏

2023-08-11 08:51 UTC, uga-rosa requested changes

2023-08-11 08:51 UTC, uga-rosa commented on denops/ddc-source-nvim-lsp/completion_item.ts
> +    const { abbr, highlights } = this.getAbbr(lspItem, this.#snippetIndicator);
`this.#snippetIndicator` is not necessary to pass it as an argument.

2023-08-11 09:09 UTC, 110y commented on denops/ddc-source-nvim-lsp/completion_item.ts
> +    const { abbr, highlights } = this.getAbbr(lspItem, this.#snippetIndicator);
Ah, that's right 🙏 Let me fix it...

2023-08-11 09:10 UTC, 110y commented on denops/ddc-source-nvim-lsp/completion_item.ts
> +    const { abbr, highlights } = this.getAbbr(lspItem, this.#snippetIndicator);
Fixed 🙏

2023-08-11 09:15 UTC, uga-rosa requested changes

2023-08-11 09:15 UTC, uga-rosa commented on denops/ddc-source-nvim-lsp/completion_item_test.ts
>    );
This line break is unnecessary.

2023-08-11 11:26 UTC, 110y commented on denops/ddc-source-nvim-lsp/completion_item_test.ts
>    );
Fixed 🙏

2023-08-11 11:41 UTC, uga-rosa commented
@Shougo please re-check

2023-08-11 11:46 UTC, Shougo approved these changes

2023-08-11 11:46 UTC, merged

2023-08-11 12:20 UTC, 110y commented
Thanks a lot!